
services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scholarsystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  backend:
    build: ./back-end
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env
    depends_on:
      - db

  frontend:
    build: ./front-end/ScholarSystem
    volumes:
      - ./front-end/ScholarSystem:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0 --poll 2000

networks:
  fullstack-net:
    driver: bridge

volumes:
  postgres_data:
