# Generated by Django 4.2 on 2025-06-19 01:27

import ScholarSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarSystem', '0002_publication_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[ScholarSystem.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[ScholarSystem.models.validate_document_file]),
        ),
    ]
