# Étape 1 : builder Angular
FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --configuration=production

# Étape 2 : nginx pour servir l'app
FROM nginx:alpine

COPY --from=build /app/dist/ScholarSystem/ /usr/share/nginx/html
EXPOSE 80
